def containerRepo = 'reedswenson/ambient-weather-exporter'
def gitBranch = env.BRANCH_NAME.replaceAll('/','_')

pipeline {
  agent none
  stages {
    stage('AMD64 Build') {
      agent {
        kubernetes {
          yamlFile '.cicd/kaniko-amd64.yaml'
        }
      }
      steps {
        script {
                  COMMIT_HASH = sh(returnStdout: true, script: "git rev-parse HEAD").trim()
                  IMAGE_TAG = "${gitBranch}-${COMMIT_HASH}"
                  echo "Tagging Image with ${IMAGE_TAG}"
              }
        container('kaniko') {
          withEnv(['PATH+EXTRA=/busybox',"IMAGE_TAG=${IMAGE_TAG}", "CACHE=false", "GIT_BRANCH=${gitBranch}", "CONTAINER_REPO=${containerRepo}"]) {
                    sh '''#!/busybox/sh
                    cat /kaniko/.docker
                    PATH=/usr/local/bin:/kaniko:/busybox /kaniko/executor \
                    -f `pwd`/Dockerfile \
                    -c `pwd` \
                    --snapshot-mode=redo \
                    --use-new-run  \
                    --cache=$CACHE \
                    --destination=$REPO:$IMAGE_TAG \
                    -v=debug
                    '''
                    }
        }
      }
    }
  }
}